#internal_team_list=''
#developer_list=''
internal_team_subject='V2 Production Repository and scan details : Auto generated email'
developer_team_subject='V2 Production full scan and review request details : Auto generated email'
internal_team_list=''
developer_list=''
from_mail_password='123'from_mail_password='123'
from_mail_password='123'
#DB configuration

prod_db_name='gamma1309'
prod_db_password='postgres'
prod_db_user='postgres'
prod_db_host='127.0.0.1'
prod_db_port='5432'
bi_db_name='bi_test'
bi_db_password='postgres'
bi_db_port='5432'
bi_db_user='postgres'
bi_db_host='127.0.0.1'
